spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: '123456'
    lettuce:
      pool:
        max-active: 10 # pool? ??? ? ?? ??? ??? (??? ?? ???)
        max-idle: 10 # pool? "idle" ??? ??? (??? ?? ???)
        min-idle: 2 # ??? ???? idle ???? ?? ? ?? (??? ?? ??)